"""Vision-language (document AI) training task module (plan 06).

Scope note (mirrors the plan's step-by-step task 3, "vision.py for one model
family (Qwen-VL)"): the heavy training path targets the Qwen2-VL family
specifically (AutoProcessor + Qwen2VLForConditionalGeneration), the
recommended-default, QLoRA-friendly model from the catalog. PaliGemma and
Florence-2 are catalogued (internal/infra/simulation/model_selector.go) as
alternatives to evaluate/add trainer support for later, per the plan's own
"verify licenses and support before finalizing" note.

The Go contract is the same one every other task module follows: JSONL
progress in job-dir/progress.jsonl, a final metrics.json, and the trained
adapter written under output_dir. Dataset records are
{"image": "<blob key>", "prompt": "...", "answer": "...", "doc_id": "...",
"page": N} — "image" resolves to a file under `images_dir` (the blob store's
per-task directory), not raw bytes, keeping the JSONL small.
"""

from __future__ import annotations

import json
import re
import signal
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

from trainer.progress import ProgressWriter

DEFAULT_TARGET_MODS = ["q_proj", "k_proj", "v_proj", "o_proj"]

# Register with the task registry at import time (idempotent).
from trainer.tasks import register  # noqa: E402  (import after module).


@dataclass
class Config:
    job_id: str
    base_model: str
    dataset_path: str
    output_dir: str
    images_dir: str = ""
    epochs: int = 3
    batch_size: int = 1
    gradient_accumulation_steps: int = 8
    learning_rate: float = 1e-4
    warmup_steps: int = 20
    max_image_side: int = 1280
    max_new_tokens: int = 256
    freeze_vision_encoder: bool = True
    lora_rank: int = 16
    lora_alpha: int = 32
    lora_dropout: float = 0.05
    lora_target_mods: list[str] = field(default_factory=lambda: list(DEFAULT_TARGET_MODS))
    load_4bit: bool = True
    grad_checkpoint: bool = True
    validation_split: float = 0.15
    max_validation_samples: int = 30
    model_cache_dir: Optional[str] = None
    resume_from: Optional[str] = None
    seed: int = 42
    # The task's JSON Schema (when the extraction output is structured), used
    # to compute a schema-valid JSON rate rather than a bare JSON-parses rate.
    json_schema: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Config":
        known = {f.name: f for f in cls.__dataclass_fields__.values()}  # type: ignore[attr-defined]
        kwargs: dict[str, Any] = {}
        for k, v in d.items():
            if k in known:
                kwargs[k] = v
        return cls(**kwargs)


def load_config(path: Path) -> Config:
    with open(path, "r", encoding="utf-8") as f:
        raw = json.load(f)
    cfg = Config.from_dict(raw)
    cfg.dataset_path = str(Path(raw.get("dataset_path", cfg.dataset_path)))
    cfg.output_dir = str(Path(raw.get("output_dir", cfg.output_dir)))
    return cfg


# --- Dataset ---.


def read_vision_records(path: Path) -> list[dict[str, Any]]:
    """Reads dataset.jsonl, skipping lines that aren't a usable vision
    example (missing image key or prompt). Mirrors read_preference_records'
    "skip the bad ones, keep the rest" contract."""
    records: list[dict[str, Any]] = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            try:
                obj = json.loads(line)
            except ValueError:
                continue

            image = str(obj.get("image", "")).strip()
            prompt = str(obj.get("prompt", "")).strip()

            if not image or not prompt:
                continue

            records.append(
                {
                    "image": image,
                    "prompt": prompt,
                    "answer": str(obj.get("answer", "")),
                    "doc_id": obj.get("doc_id", ""),
                    "page": obj.get("page", 0),
                }
            )

    return records


def resolve_image_path(images_dir: str, image_key: str) -> Path:
    """Resolves a dataset record's blob key to a file path under
    images_dir. filepath traversal is neutralized by taking only the
    basename -- image keys are opaque IDs generated by the blob store, never
    user-supplied paths."""
    return Path(images_dir) / Path(image_key).name


def load_pil_image(images_dir: str, image_key: str, max_side: int):
    """Loads and (if needed) downsamples one training image. Imports PIL
    lazily so importing this module for its pure functions (tests, the CLI's
    --help) doesn't require Pillow to be installed."""
    from PIL import Image

    path = resolve_image_path(images_dir, image_key)
    img = Image.open(path).convert("RGB")

    if max_side > 0 and max(img.size) > max_side:
        scale = max_side / max(img.size)
        new_size = (max(1, int(img.width * scale)), max(1, int(img.height * scale)))
        img = img.resize(new_size, Image.LANCZOS)

    return img


# --- Field-level evaluation (invoice/receipt-style extraction) ---.


def try_parse_json(text: str) -> Optional[dict[str, Any]]:
    """Best-effort JSON object parse: strips a ```json ... ``` fence some
    models wrap structured output in, then attempts a strict parse."""
    text = text.strip()

    fence = re.match(r"^```(?:json)?\s*(.*?)\s*```$", text, re.DOTALL)
    if fence:
        text = fence.group(1).strip()

    try:
        parsed = json.loads(text)
    except (TypeError, ValueError):
        return None

    return parsed if isinstance(parsed, dict) else None


_NORMALIZE_STRIP_RE = re.compile(r"[,$%\s]")


def normalize_field_value(value: Any) -> str:
    """Normalizes a field value for comparison: numbers/dates/amounts vary in
    formatting (",", "$", trailing whitespace) far more than in substance, so
    exact-match on the raw string would understate real quality (plan 06,
    section 9: "exact match and F1 ... with normalization for amounts/dates")."""
    s = str(value).strip().lower()
    return _NORMALIZE_STRIP_RE.sub("", s)


def _token_f1(pred: str, gold: str) -> float:
    """SQuAD-style token-overlap F1 between two normalized strings."""
    pred_toks = list(pred)
    gold_toks = list(gold)

    if not pred_toks and not gold_toks:
        return 1.0

    if not pred_toks or not gold_toks:
        return 0.0

    common: dict[str, int] = {}
    for c in pred_toks:
        common[c] = common.get(c, 0) + 1

    overlap = 0
    for c in gold_toks:
        if common.get(c, 0) > 0:
            overlap += 1
            common[c] -= 1

    if overlap == 0:
        return 0.0

    precision = overlap / len(pred_toks)
    recall = overlap / len(gold_toks)

    return round(2 * precision * recall / (precision + recall), 4)


def field_level_metrics(
    predictions: list[Optional[dict[str, Any]]],
    golds: list[dict[str, Any]],
) -> dict[str, dict[str, float]]:
    """Computes per-field exact-match/F1/support over parsed JSON
    predictions vs. gold answers. A prediction of None (failed to parse, or
    the field is simply absent) counts as a miss for every gold field."""
    fields: dict[str, list[tuple[float, float]]] = {}

    for pred, gold in zip(predictions, golds):
        for key, gold_val in gold.items():
            gold_norm = normalize_field_value(gold_val)
            pred_val = pred.get(key) if isinstance(pred, dict) else None
            pred_norm = normalize_field_value(pred_val) if pred_val is not None else ""

            exact = 1.0 if pred_norm == gold_norm else 0.0
            f1 = _token_f1(pred_norm, gold_norm)

            fields.setdefault(key, []).append((exact, f1))

    out: dict[str, dict[str, float]] = {}

    for key, pairs in fields.items():
        n = len(pairs)
        out[key] = {
            "exact_match": round(sum(p[0] for p in pairs) / n, 4),
            "f1": round(sum(p[1] for p in pairs) / n, 4),
            "support": n,
        }

    return out


def macro_field_f1(field_metrics: dict[str, dict[str, float]]) -> float:
    if not field_metrics:
        return 0.0

    return round(sum(m["f1"] for m in field_metrics.values()) / len(field_metrics), 4)


def document_accuracy(predictions: list[Optional[dict[str, Any]]], golds: list[dict[str, Any]]) -> float:
    """Fraction of examples where every gold field matched exactly (plan's
    "document-level accuracy (all fields correct)")."""
    if not golds:
        return 0.0

    correct = 0

    for pred, gold in zip(predictions, golds):
        if not isinstance(pred, dict):
            continue

        if all(normalize_field_value(pred.get(k)) == normalize_field_value(v) for k, v in gold.items()):
            correct += 1

    return round(correct / len(golds), 4)


def _levenshtein(a: str, b: str) -> int:
    if a == b:
        return 0

    if not a:
        return len(b)

    if not b:
        return len(a)

    prev = list(range(len(b) + 1))

    for i, ca in enumerate(a, start=1):
        cur = [i] + [0] * len(b)

        for j, cb in enumerate(b, start=1):
            cost = 0 if ca == cb else 1
            cur[j] = min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + cost)

        prev = cur

    return prev[-1]


def anls_score(pred: str, gold: str) -> float:
    """Normalized Levenshtein Similarity for one (pred, gold) pair, the
    standard document-VQA metric for free-text answers. Scores below 0.5 are
    clamped to 0 per the ANLS convention (a "wrong enough" answer shouldn't
    get partial credit just for sharing characters)."""
    pred, gold = pred.strip().lower(), gold.strip().lower()

    if not gold:
        return 1.0 if not pred else 0.0

    dist = _levenshtein(pred, gold)
    nls = 1 - dist / max(len(pred), len(gold), 1)

    return round(nls, 4) if nls >= 0.5 else 0.0


def average_anls(predictions: list[str], golds: list[str]) -> float:
    if not golds:
        return 0.0

    scores = [anls_score(p, g) for p, g in zip(predictions, golds)]

    return round(sum(scores) / len(scores), 4)


def json_validity_rate(predictions: list[str], schema_str: Optional[str]) -> float:
    """Fraction of predictions that parse as JSON, and — when a schema is
    given — also satisfy it."""
    if not predictions:
        return 0.0

    validator = None

    if schema_str:
        try:
            import jsonschema  # type: ignore

            validator = jsonschema.Draft7Validator(json.loads(schema_str))
        except Exception:  # noqa: BLE001 - fall back to parse-only below.
            validator = None

    valid = 0

    for text in predictions:
        parsed = try_parse_json(text)
        if parsed is None:
            continue

        if validator is not None and not validator.is_valid(parsed):
            continue

        valid += 1

    return round(valid / len(predictions), 4)


def evaluate_predictions(
    predicted_texts: list[str],
    gold_answers: list[str],
    schema_str: Optional[str],
) -> dict[str, Any]:
    """Runs the full plan-9 metric suite over a held-out split's generations.
    Field metrics are computed only when every gold answer parses as JSON
    (the invoice/receipt/form extraction case); otherwise the free-text ANLS
    path is used."""
    gold_parsed = [try_parse_json(g) for g in gold_answers]
    is_structured = bool(gold_answers) and all(g is not None for g in gold_parsed)

    metrics: dict[str, Any] = {
        "json_valid_rate": json_validity_rate(predicted_texts, schema_str),
    }

    if is_structured:
        pred_parsed = [try_parse_json(t) for t in predicted_texts]
        fm = field_level_metrics(pred_parsed, gold_parsed)  # type: ignore[arg-type]
        metrics["field_metrics"] = fm
        metrics["macro_field_f1"] = macro_field_f1(fm)
        metrics["document_accuracy"] = document_accuracy(pred_parsed, gold_parsed)  # type: ignore[arg-type]
    else:
        metrics["anls"] = average_anls(predicted_texts, gold_answers)

    return metrics


# --- Training ---.


class DistilleryProgressCallback:
    """Emits one JSON progress line per on_log event (mirrors sft.py's)."""

    def __init__(self, writer: ProgressWriter, total_steps: int):
        self.writer = writer
        self.total_steps = total_steps

    def on_log(self, args, state, control, logs=None):  # noqa: ARG002
        loss = logs.get("loss") if logs else None
        eval_loss = logs.get("eval_loss") if logs else None
        lr = logs.get("learning_rate") if logs else None
        self.writer.progress(
            step=state.global_step,
            total_steps=self.total_steps,
            epoch=state.epoch,
            loss=loss,
            eval_loss=eval_loss,
            lr=lr,
        )


def save_metrics(output_dir: Path, metrics: dict[str, Any]) -> None:
    metrics_path = output_dir / "metrics.json"
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2, ensure_ascii=False)
    print(f"metrics written to {metrics_path}", file=sys.stderr)


def _build_collate_fn(processor, max_image_side: int, images_dir: str):
    """Builds the multimodal collate function: renders each record's chat
    turns through the processor's chat template, tokenizes prompt+answer
    together, and masks the prompt (+ padding) tokens out of the loss so
    only the answer contributes to the gradient -- the same "mask
    non-answer tokens" contract sft.py's tokenizer path follows for plain
    text."""
    import torch

    def _messages(prompt: str, answer: Optional[str]):
        user_turn = {"role": "user", "content": [{"type": "image"}, {"type": "text", "text": prompt}]}
        if answer is None:
            return [user_turn]
        return [user_turn, {"role": "assistant", "content": [{"type": "text", "text": answer}]}]

    def collate(batch: list[dict[str, Any]]):
        images = [load_pil_image(images_dir, r["image"], max_image_side) for r in batch]

        prompt_texts = [
            processor.apply_chat_template(_messages(r["prompt"], None), tokenize=False, add_generation_prompt=True)
            for r in batch
        ]
        full_texts = [
            processor.apply_chat_template(_messages(r["prompt"], r["answer"]), tokenize=False, add_generation_prompt=False)
            for r in batch
        ]

        prompt_enc = processor(text=prompt_texts, images=images, padding=True, truncation=True, return_tensors="pt")
        full_enc = processor(text=full_texts, images=images, padding=True, truncation=True, return_tensors="pt")

        labels = full_enc["input_ids"].clone()
        pad_id = processor.tokenizer.pad_token_id

        for i in range(labels.size(0)):
            prompt_len = int(prompt_enc["attention_mask"][i].sum().item())
            labels[i, :prompt_len] = -100

        labels[full_enc["input_ids"] == pad_id] = -100

        full_enc["labels"] = labels

        return full_enc

    return collate


def run(cfg: Config, writer: ProgressWriter, job_dir: Path, dataset_path: str) -> int:
    """Runs the vision-language QLoRA fine-tune and returns the process exit code."""
    stop_requested = False

    def handle_sigterm(signum, frame):  # noqa: ARG001
        nonlocal stop_requested
        stop_requested = True
        writer.event("signal", signal="SIGTERM", msg="graceful stop requested")

    signal.signal(signal.SIGTERM, handle_sigterm)

    if not cfg.images_dir:
        writer.event("error", message="images_dir is required for vision_lm training")
        save_metrics(job_dir, {"status": "failed", "error": "images_dir is required"})
        return 1

    # --- Import heavy libs lazily so --help / config errors are cheap. ---
    import torch
    from transformers import AutoProcessor, BitsAndBytesConfig, Qwen2VLForConditionalGeneration, TrainingArguments
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

    device_map = "auto"
    if torch.cuda.is_available():
        writer.event("device", device_type="cuda", name=torch.cuda.get_device_name(0))
    else:
        writer.event("device", device_type="cpu")
        device_map = "cpu"

    try:
        processor = AutoProcessor.from_pretrained(cfg.base_model, cache_dir=cfg.model_cache_dir, trust_remote_code=True)

        model_kwargs: dict[str, Any] = {
            "cache_dir": cfg.model_cache_dir,
            "device_map": device_map,
            "trust_remote_code": True,
        }

        if cfg.load_4bit and torch.cuda.is_available():
            model_kwargs["quantization_config"] = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=torch.float16,
                bnb_4bit_use_double_quant=True,
            )

        model = Qwen2VLForConditionalGeneration.from_pretrained(cfg.base_model, **model_kwargs)

        # Freeze the vision tower by default (plan: "freeze the vision
        # encoder by default") -- LoRA trains only the language tower
        # (+ optionally the projector), which is what keeps VRAM in reach of
        # a single consumer GPU for a 2B-7B VLM.
        if cfg.freeze_vision_encoder and hasattr(model, "visual"):
            for p in model.visual.parameters():
                p.requires_grad_(False)

        if cfg.load_4bit and torch.cuda.is_available():
            model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=cfg.grad_checkpoint)

        lora_config = LoraConfig(
            r=cfg.lora_rank,
            lora_alpha=cfg.lora_alpha,
            lora_dropout=cfg.lora_dropout,
            target_modules=cfg.lora_target_mods or DEFAULT_TARGET_MODS,
            task_type="CAUSAL_LM",
        )
        model = get_peft_model(model, lora_config)
        model.print_trainable_parameters()

        records = read_vision_records(Path(dataset_path))
        if not records:
            raise ValueError("Dataset is empty or has no readable vision records")

        if cfg.validation_split > 0 and len(records) >= 5:
            cut = max(1, int(len(records) * (1 - cfg.validation_split)))
            train_records, eval_records = records[:cut], records[cut:]
        else:
            train_records, eval_records = records, []

        collate_fn = _build_collate_fn(processor, cfg.max_image_side, cfg.images_dir)

        class _ListDataset(torch.utils.data.Dataset):
            def __init__(self, items: list[dict[str, Any]]):
                self.items = items

            def __len__(self) -> int:
                return len(self.items)

            def __getitem__(self, idx: int) -> dict[str, Any]:
                return self.items[idx]

        train_ds = _ListDataset(train_records)

        output_dir = Path(cfg.output_dir)
        checkpoint_dir = output_dir / "checkpoints"
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

        training_args = TrainingArguments(
            output_dir=str(checkpoint_dir),
            num_train_epochs=cfg.epochs,
            per_device_train_batch_size=cfg.batch_size,
            gradient_accumulation_steps=cfg.gradient_accumulation_steps,
            learning_rate=cfg.learning_rate,
            warmup_steps=cfg.warmup_steps,
            logging_steps=1,
            save_strategy="epoch",
            save_total_limit=2,
            report_to=[],
            seed=cfg.seed,
            fp16=torch.cuda.is_available(),
            gradient_checkpointing=cfg.grad_checkpoint,
            remove_unused_columns=False,
        )

        total_steps = max(1, len(train_ds) // (cfg.batch_size * cfg.gradient_accumulation_steps)) * cfg.epochs
        callback = DistilleryProgressCallback(writer, total_steps)

        from transformers import Trainer

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_ds,
            data_collator=collate_fn,
            callbacks=[callback],
        )

        writer.event("status", value="starting_training", total_steps=total_steps)

        trainer.train(resume_from_checkpoint=cfg.resume_from)

        adapter_path = output_dir / "adapter"
        model.save_pretrained(str(adapter_path))
        processor.save_pretrained(str(output_dir / "processor"))

        final_metrics: dict[str, Any] = {"status": "completed", "kind": "vision_lm", "train_examples": len(train_records)}

        # Held-out generation + the plan-9 metric suite (field F1, ANLS, JSON
        # validity, document accuracy), bounded by max_validation_samples the
        # same way sft.py bounds its JSON-validity generation pass.
        if eval_records:
            sample = eval_records[: cfg.max_validation_samples]
            gold_answers = [r["answer"] for r in sample]

            predicted_texts = _generate_predictions(model, processor, sample, cfg)
            final_metrics.update(evaluate_predictions(predicted_texts, gold_answers, cfg.json_schema))

            # Zero-shot baseline: the plan's definition of done is "beats a
            # zero-shot baseline on field F1", so re-run generation with the
            # LoRA adapter disabled -- the base VLM, prompted the same way,
            # at no extra load cost since it's the same model object already
            # in memory. This differs from classifier.py's majority-class
            # "sanity floor" baseline, which stands in for a real zero-shot
            # pass that isn't cheaply available there; here a true zero-shot
            # comparison IS cheap (peft's disable_adapter), so we use it.
            if hasattr(model, "disable_adapter"):
                with model.disable_adapter():
                    baseline_texts = _generate_predictions(model, processor, sample, cfg)
                baseline_metrics = evaluate_predictions(baseline_texts, gold_answers, cfg.json_schema)
                baseline_field_f1 = baseline_metrics.get("macro_field_f1")
                if baseline_field_f1 is not None and "macro_field_f1" in final_metrics:
                    final_metrics["baseline_field_f1"] = baseline_field_f1
                    final_metrics["delta_field_f1"] = round(final_metrics["macro_field_f1"] - baseline_field_f1, 4)

            writer.event("eval", **{k: v for k, v in final_metrics.items() if k not in ("status", "kind")})

        writer.event("complete", status="completed", kind="vision_lm")
        save_metrics(job_dir, final_metrics)

        if stop_requested:
            writer.event("status", value="stopped_by_user")
            return 130

        return 0

    except Exception as exc:  # noqa: BLE001
        writer.event("error", message=str(exc), class_name=type(exc).__name__)
        save_metrics(job_dir, {"status": "failed", "error": str(exc)})
        print(f"FATAL: {exc}", file=sys.stderr)
        return 1
    finally:
        writer.close()


def _generate_predictions(model, processor, records: list[dict[str, Any]], cfg: Config) -> list[str]:
    """Greedy-generates the model's answer for each held-out record."""
    import torch

    model.eval()
    outputs: list[str] = []

    with torch.no_grad():
        for r in records:
            image = load_pil_image(cfg.images_dir, r["image"], cfg.max_image_side)
            messages = [{"role": "user", "content": [{"type": "image"}, {"type": "text", "text": r["prompt"]}]}]
            text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

            inputs = processor(text=[text], images=[image], return_tensors="pt")
            inputs = {k: v.to(model.device) for k, v in inputs.items()}

            generated = model.generate(**inputs, max_new_tokens=cfg.max_new_tokens, do_sample=False)
            new_tokens = generated[:, inputs["input_ids"].shape[1] :]
            outputs.append(processor.batch_decode(new_tokens, skip_special_tokens=True)[0].strip())

    return outputs


def _runner(cfg_dict: dict, writer: object, job_dir: str, dataset_path: str) -> int:
    c = cfg_dict if isinstance(cfg_dict, Config) else Config.from_dict(cfg_dict)
    c.dataset_path = dataset_path or c.dataset_path

    return run(c, writer, Path(job_dir), c.dataset_path)


register("vision_lm", _runner)
